env:
  browser: true
  es2021: true
  node: true
  'vue/setup-compiler-macros': true

extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-essential'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:vue/vue3-strongly-recommended'
  - '@vue/airbnb'
  - '@vue/typescript'
  - 'prettier'

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - 'peachy-stories/app/tsconfig.json'
    - 'peachy-stories/app/tsconfig.node.json'
    - 'peachy-stories/core/tsconfig.json'
    - 'example/tsconfig.json'
    - 'example/tsconfig.node.json'

plugins:
  - 'vue'
  - '@typescript-eslint'
  - 'import'
  - 'prettier'

rules:
  indent:
    - error
    - tab

  linebreak-style:
    - error
    - unix

  quotes:
    - error
    - single

  semi:
    - error
    - always

  complexity:
    - error
    - 10

  'class-methods-use-this': error
  'default-case-last': error
  'consistent-return': off

  'no-plusplus': off
  'no-multiple-empty-lines': error
  'no-underscore-dangle': off
  'import/no-extraneous-dependencies': off

  'import/prefer-default-export': off

  'import/no-unresolved':
    - error
    - ignore:
        - '^\$'

  'import/extensions':
    - error
    - ignorePackages
    - js: never
      ts: never

  '@typescript-eslint/ban-types': warn
  '@typescript-eslint/no-shadow': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-unsafe-argument': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/no-unsafe-call': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/no-unsafe-assignment': off

  'vue/no-mutating-props': 'warn'
  'vue/no-setup-props-destructure': 'warn'
  'vue/multi-word-component-names': 'warn'

  'no-console':
    - warn
    - allow:
        - error
        - assert
        - warn

  'prefer-destructuring':
    - error
    - object: true
      array: false

  'vue/script-indent':
    - error
    - 'tab'
    - baseIndent: 1
      switchCase: 1

overrides:
  - files:
      - '*.vue'
    parser: 'vue-eslint-parser'
    rules:
      indent: off

settings:
  'import/resolver':
    typescript:
      project:
        - 'peachy-stories/app/tsconfig.json'
        - 'peachy-stories/app/tsconfig.node.json'
        - 'peachy-stories/core/tsconfig.json'
        - 'example/tsconfig.json'
        - 'example/tsconfig.node.json'
      node:
        extensions:
          - '.js'
          - '.ts'
